### ISSUE TITLE
Additional regional aggregations (REMIND)

### ISSUE THREAD

**Issue by Renato-Rodrigues** [openENTRANCE/openentrance#119]
Request to add support for REMIND regions aggregation for use in the ECEMF project.

Additional regional aggregations:

```
World:
   definition: 'all World countries'

EU27+UK:
   definition: 'EU27 plus United Kingdom' 

UKI:
   definition: 'United Kingdom and Ireland'

NEU:
   definition: 'European countries outside EU (minus UK)'
   
NEN:
   definition: 'Non European Union North countries'
   
NES:
   definition: 'Non European Union South countries'

ECE:	
   definition: 'European Union Center East countries'

ENC:
   definition: 'European Union North Center countries'

ECS:	
   definition: 'European Union Center South'

ESC:	
   definition: 'European Union South Center countries'

ESW:	
   definition: 'European Union South West countries'

EWN:	
   definition: 'European Union West North countries'
```

You can find the detailed mapping of the above mentioned regions in the below file: 
https://github.com/remindmodel/remind/blob/develop/config/21_regions_EU11/regionmapping_21_EU11.csv
region names (column 2), iso-3 codes (column 2):
