### ISSUE TITLE
Empty units

### ISSUE THREAD

**Issue by sandrinecharousset** [openENTRANCE/openentrance#198]
Some variables do have an empty unit in the nomenclature (eg roundtrip efficiency), but when trying to upload it raises an error : '' not accepted as unit
What should we do?
@danielhuppmann maybe I missed something....

**Comment by danielhuppmann** [comment]
Apologies for the late response, please use the following
```yaml
- <Variable>:
    description: <description>
    unit: "-"
```
This is an issue in the underlying ixmp database infrastructure behind the IIASA Scenario Explorer.
